A = int(input("Enter the value of A: "))
B = int(input("Enter the value of B: "))
C = int(input("Enter the value of C: "))
D = int(input("Enter the value of D: "))

print("\nAddition Results:")
print(f"A + B = {A + B}")
print(f"A + C = {A + C}")
print(f"A + D = {A + D}")
print(f"B + C = {B + C}")
print(f"B + D = {B + D}")
print(f"C + D = {C + D}")

print("\nMultiplication Results:")
print(f"A * B = {A * B}")
print(f"A * C = {A * C}")
print(f"A * D = {A * D}")
print(f"B * C = {B * C}")
print(f"B * D = {B * D}")
print(f"C * D = {C * D}")
